server:
  port: 8081

spring:
  application:
    name: pizzaria-service

  datasource:
    url: jdbc:h2:mem:pizzadb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  sql:
    init:
      mode: always
    schema-locations: classpath:schema.sql
    data-locations: classpath:data.sql

  h2:
    console:
      enabled: true
      path: /h2-console

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

app:
  imposto:
    codigo: ${IMPOSTO_CODIGO:LEI_10}
  desconto:
    codigo: ${DESCONTO_CODIGO:FIDELIDADE}
